# Generated by Django 4.2.2 on 2025-08-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="reward",
            new_name="award",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="is_pleasant",
            new_name="is_nice",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="frequency",
            new_name="period",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="linked_habit",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="time",
        ),
        migrations.AddField(
            model_name="habit",
            name="associated_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="associated_to",
                to="habit_tracker.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="habit_time",
            field=models.DateTimeField(null=True, verbose_name="Время"),
        ),
    ]
